# Generated by Django 6.0.1 on 2026-03-10 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0001_initial'),
        ('patients', '0005_patient_age_patient_allergies_patient_clinical_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_physician', models.CharField(max_length=200)),
                ('scan_type', models.CharField(default='CT', max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='REGISTERED', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_registrations', to='patients.patient')),
            ],
        ),
    ]
