# Generated by Django 6.0.1 on 2026-03-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom', '0002_scanregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomscan',
            name='modality',
            field=models.CharField(blank=True, help_text='e.g., CT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dicomscan',
            name='protocol_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dicomscan',
            name='series_instance_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dicomscan',
            name='study_instance_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
