# Generated by Django 6.0.1 on 2026-03-07 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('confidence_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50)),
                ('high_risk_value', models.IntegerField(default=0)),
                ('high_risk_desc', models.CharField(default='Processing...', max_length=200)),
                ('pediatric_risk_value', models.IntegerField(default=0)),
                ('pediatric_risk_desc', models.CharField(default='Processing...', max_length=200)),
                ('protocol_deviations_value', models.IntegerField(default=0)),
                ('protocol_deviations_desc', models.CharField(default='Processing...', max_length=200)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='patients.patient')),
            ],
        ),
    ]
