# Generated by Django 6.0.1 on 2026-03-07 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField()),
                ('study_description', models.CharField(max_length=200)),
                ('total_dlp', models.FloatField(help_text='Total Dose Length Product')),
                ('avg_risk', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_doses', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OrganDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(max_length=100)),
                ('dose_value', models.FloatField()),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_doses', to='dosestats.scandose')),
            ],
        ),
    ]
