# Generated by Django 6.0.1 on 2026-03-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosestats', '0001_initial'),
        ('patients', '0003_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_id', models.CharField(help_text='#PX-000', max_length=50, unique=True)),
                ('area', models.CharField(help_text='e.g., Head, Chest', max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('dlp_value', models.FloatField(help_text='Dose Length Product')),
                ('status_level', models.CharField(choices=[('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL'), ('REVIEW', 'REVIEW')], max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='patients.patient')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
