# Generated by Django 6.0.1 on 2026-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosestats', '0002_doseanomaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='scandose',
            name='facility',
            field=models.CharField(default='Facility A', help_text='e.g., Facility A', max_length=200),
        ),
    ]
