# Generated by Django 6.0.1 on 2026-03-10 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosestats', '0003_scandose_facility'),
        ('patients', '0006_patient_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kvp', models.FloatField(help_text='kVp value from Scan Parameters screen')),
                ('ma', models.FloatField(help_text='mA value from Scan Parameters screen')),
                ('pitch', models.FloatField(help_text='Pitch value from Scan Parameters screen')),
                ('scan_length', models.FloatField(help_text='Scan Length (mm) from Scan Parameters screen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_parameters', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
