# Generated by Django 6.0.1 on 2026-03-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='title',
            field=models.CharField(default='New Report', max_length=200),
        ),
    ]
