# Generated by Django 6.0.1 on 2026-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description_1', models.CharField(blank=True, max_length=500, null=True)),
                ('description_2', models.CharField(blank=True, max_length=500, null=True)),
                ('description_3', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
