# Generated by Django 6.0.1 on 2026-03-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincenter', '0006_systemlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
