# Generated by Django 6.0.1 on 2026-03-07 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dose_rate', models.FloatField(help_text='Current dose rate in mGy/s')),
                ('accumulated_dose', models.FloatField(help_text='Total accumulated dose during this session')),
                ('is_active', models.BooleanField(default=True, help_text='Is the procedure still ongoing?')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_doses', to='patients.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
