# Generated by Django 6.0.1 on 2026-03-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_level',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARNING', 'WARNING'), ('CRITICAL', 'CRITICAL')], default='INFO', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='dose_value_mSv',
            field=models.FloatField(blank=True, help_text='Measured dose related to the alert', null=True),
        ),
    ]
