# Generated by Django 6.0.1 on 2026-03-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alert_alert_level_alert_dose_value_msv'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
