# Generated by Django 6.0.3 on 2026-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
